import React, { useState, useEffect } from "react";
import { X, Plus, Clock, User, AlertCircle, CheckCircle } from "lucide-react";
import toast from "react-hot-toast";
import api from "@/lib/api";

interface OnboardingTemplate {
  id: string;
  name: string;
  description: string | null;
  isDefault: boolean;
  tasks: OnboardingTask[];
}

interface OnboardingTask {
  id: string;
  title: string;
  description: string | null;
  category: string | null;
  priority: string | null;
  estimatedHours: number | null;
  order: number;
}

interface Client {
  id: string;
  name: string;
  domain: string;
}

interface User {
  id: string;
  name: string;
  email: string;
}

interface OnboardingTemplateModalProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  onTasksCreated: () => void;
  /** When opening from a client context (e.g. Client Dashboard), preselect this client */
  initialClientId?: string;
}

const OnboardingTemplateModal: React.FC<OnboardingTemplateModalProps> = ({
  open,
  setOpen,
  onTasksCreated,
  initialClientId,
}) => {
  const [templates, setTemplates] = useState<OnboardingTemplate[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [workers, setWorkers] = useState<User[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<OnboardingTemplate | null>(null);
  const [selectedClient, setSelectedClient] = useState<string>(initialClientId || "");
  const [selectedWorker, setSelectedWorker] = useState<string>("");
  const [onboardingStartDate, setOnboardingStartDate] = useState<Date>(() => new Date());
  const [autoGenerateDeliverables, setAutoGenerateDeliverables] = useState(true);
  const [initialDueDate, setInitialDueDate] = useState<Date>(() => {
    const now = new Date();
    return now;
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>("");

  const INITIAL_DUE_DATE_BUSINESS_DAYS = 3;
  const INITIAL_DUE_DATE_TASK_COUNT = 4; // only the first 3–4 tasks get due dates (set to 4)
  const DELIVERABLES_START_DAY_CUTOFF = 20; // if start date is before this day, include current month

  const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  const addBusinessDays = (start: Date, businessDays: number) => {
    const d = new Date(start);
    d.setHours(0, 0, 0, 0);
    let added = 0;
    while (added < businessDays) {
      d.setDate(d.getDate() + 1);
      const day = d.getDay();
      // 0 = Sunday, 6 = Saturday
      if (day !== 0 && day !== 6) {
        added += 1;
      }
    }
    return d;
  };

  const formatYYYYMMDD = (d: Date) => {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  };

  const initialDueDateStr = formatYYYYMMDD(initialDueDate);
  const onboardingStartDateStr = formatYYYYMMDD(onboardingStartDate);

  const parseYYYYMMDD = (value: string): Date => {
    // Parse as local date to avoid timezone shifts.
    const [y, m, d] = value.split("-").map((p) => Number(p));
    return new Date(y, (m || 1) - 1, d || 1);
  };

  const getDeliverablesStartMonth = (start: Date) => {
    const d = new Date(start);
    d.setHours(0, 0, 0, 0);
    // If start date is before the 20th, current month counts; otherwise start next month.
    if (d.getDate() < DELIVERABLES_START_DAY_CUTOFF) {
      return new Date(d.getFullYear(), d.getMonth(), 1);
    }
    return new Date(d.getFullYear(), d.getMonth() + 1, 1);
  };

  const endOfMonth = (monthStart: Date) => {
    const d = new Date(monthStart.getFullYear(), monthStart.getMonth() + 1, 0);
    d.setHours(0, 0, 0, 0);
    return d;
  };

  const buildMonthlyDeliverablesTasks = () => {
    const firstMonth = getDeliverablesStartMonth(onboardingStartDate);
    return Array.from({ length: 12 }).map((_, idx) => {
      const monthStart = new Date(firstMonth.getFullYear(), firstMonth.getMonth() + idx, 1);
      const monthLabel = `${monthNames[monthStart.getMonth()]} ${monthStart.getFullYear()}`;
      return {
        title: `Monthly Deliverables - ${monthLabel}`,
        description: `Monthly deliverables for ${monthLabel}.`,
        category: "Deliverables",
        status: "TODO" as const,
        clientId: selectedClient,
        assigneeId: selectedWorker || null,
        dueDate: formatYYYYMMDD(endOfMonth(monthStart)),
        priority: "medium",
      };
    });
  };

  const getDeliverablesRangeLabel = () => {
    const first = getDeliverablesStartMonth(onboardingStartDate);
    const last = new Date(first.getFullYear(), first.getMonth() + 11, 1);
    return `${monthNames[first.getMonth()]} ${first.getFullYear()} – ${monthNames[last.getMonth()]} ${last.getFullYear()}`;
  };

  // Fetch templates, clients, and workers on modal open
  useEffect(() => {
    if (open) {
      setSelectedClient(initialClientId || "");
      setInitialDueDate(addBusinessDays(new Date(), INITIAL_DUE_DATE_BUSINESS_DAYS));
      setOnboardingStartDate(new Date());
      fetchTemplates();
      fetchClients();
      fetchWorkers();
    }
  }, [open, initialClientId]);

  // Preselect client once clients list is loaded (e.g. when opened from Client Dashboard)
  useEffect(() => {
    if (open && initialClientId && clients.length > 0 && clients.some((c) => c.id === initialClientId)) {
      setSelectedClient(initialClientId);
    }
  }, [open, initialClientId, clients]);

  const fetchTemplates = async () => {
    try {
      const response = await api.get("/onboarding/templates");
      const data = response.data;
      setTemplates(Array.isArray(data) ? data : Array.isArray(data?.templates) ? data.templates : []);
    } catch (error: any) {
      console.error("Error fetching templates:", error);
      setTemplates([]);
      // Toast is already shown by API interceptor
    }
  };

  const fetchClients = async () => {
    try {
      const response = await api.get("/clients");
      const list = Array.isArray(response.data) ? response.data : [];
      list.sort((a: Client, b: Client) =>
        (a.name || "").localeCompare(b.name || "", undefined, { sensitivity: "base" })
      );
      setClients(list);
    } catch (error: any) {
      console.error("Error fetching clients:", error);
      // Toast is already shown by API interceptor
    }
  };

  const fetchWorkers = async () => {
    try {
      const response = await api.get("/auth/workers");
      setWorkers(response.data);
    } catch (error: any) {
      console.error("Error fetching workers:", error);
      // Toast is already shown by API interceptor
    }
  };

  const handleCreateTasks = async () => {
    if (!selectedTemplate || !selectedClient) {
      setError("Please select a template and client");
      return;
    }

    setLoading(true);
    setError("");

    try {
      const tasks = selectedTemplate.tasks.map((templateTask) => ({
        title: templateTask.title,
        description: templateTask.description ?? undefined,
        category: templateTask.category ?? undefined,
        status: "TODO" as const,
        clientId: selectedClient,
        assigneeId: selectedWorker || null,
        // Only the first few onboarding tasks get an automatic due date.
        // All other tasks require manual due dates.
        dueDate:
          templateTask.order > 0 && templateTask.order <= INITIAL_DUE_DATE_TASK_COUNT
            ? initialDueDateStr
            : null,
        estimatedHours: templateTask.estimatedHours ?? undefined,
        priority: templateTask.priority ?? undefined,
      }));

      const deliverablesTasks = autoGenerateDeliverables ? buildMonthlyDeliverablesTasks() : [];

      const allTasks = [...tasks, ...deliverablesTasks];

      await api.post("/tasks/bulk", { tasks: allTasks });
      
      toast.success(
        `Successfully created ${allTasks.length} task${allTasks.length > 1 ? "s" : ""}!`
      );
      onTasksCreated();
      setOpen(false);
      resetForm();
    } catch (error: any) {
      const errorMsg = error.response?.data?.message || "Failed to create tasks";
      setError(errorMsg);
      // Toast is already shown by API interceptor
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setSelectedTemplate(null);
    setSelectedClient("");
    setSelectedWorker("");
    setOnboardingStartDate(new Date());
    setAutoGenerateDeliverables(true);
    setError("");
  };

  const getPriorityColor = (priority: string | null) => {
    switch (priority) {
      case "high":
        return "text-red-600 bg-red-100";
      case "medium":
        return "text-yellow-600 bg-yellow-100";
      case "low":
        return "text-green-600 bg-green-100";
      default:
        return "text-gray-600 bg-gray-100";
    }
  };

  const getPriorityIcon = (priority: string | null) => {
    switch (priority) {
      case "high":
        return <AlertCircle className="h-3 w-3" />;
      case "medium":
        return <Clock className="h-3 w-3" />;
      case "low":
        return <CheckCircle className="h-3 w-3" />;
      default:
        return <Clock className="h-3 w-3" />;
    }
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-xl max-w-4xl w-full max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 flex-shrink-0">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Create Onboarding Tasks</h2>
            <p className="text-gray-600 mt-1">Generate tasks from predefined templates for new clients</p>
          </div>
          <button
            onClick={() => setOpen(false)}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="h-6 w-6 text-gray-500" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto flex-1 min-h-0">
          {error && (
            <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg">
              <div className="flex items-center">
                <AlertCircle className="h-5 w-5 text-red-500 mr-2" />
                <span className="text-red-700">{error}</span>
              </div>
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Template Selection */}
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Select Template</h3>
              <div className="space-y-3">
                {templates.length === 0 ? (
                  <p className="text-sm text-gray-500 py-4">No templates available. Loading or creating default…</p>
                ) : null}
                {templates.map((template) => (
                  <div
                    key={template.id}
                    onClick={() => setSelectedTemplate(template)}
                    className={`p-4 border rounded-lg cursor-pointer transition-colors ${
                      selectedTemplate?.id === template.id
                        ? "border-primary-500 bg-primary-50"
                        : "border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <h4 className="font-medium text-gray-900">{template.name}</h4>
                        {template.description && (
                          <p className="text-sm text-gray-600 mt-1">{template.description}</p>
                        )}
                        <p className="text-xs text-gray-500 mt-1">
                          {template.tasks.length} tasks • {template.tasks.reduce((sum, task) => sum + (task.estimatedHours || 0), 0)} hours
                        </p>
                      </div>
                      {template.isDefault && (
                        <span className="px-2 py-1 text-xs font-medium text-primary-600 bg-primary-100 rounded-full">
                          Default
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Configuration */}
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Configuration</h3>
              <div className="space-y-4">
                {/* Client Selection */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Client *
                  </label>
                  <select
                    value={selectedClient}
                    onChange={(e) => setSelectedClient(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  >
                    <option value="">Select a client</option>
                    {clients.map((client) => (
                      <option key={client.id} value={client.id}>
                        {client.name} ({client.domain})
                      </option>
                    ))}
                  </select>
                </div>

                {/* Specialist Assignment */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Assign to Specialist
                  </label>
                  <select
                    value={selectedWorker}
                    onChange={(e) => setSelectedWorker(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  >
                    <option value="">Unassigned</option>
                    {workers.map((worker) => (
                      <option key={worker.id} value={worker.id}>
                        {worker.name} ({worker.email})
                      </option>
                    ))}
                  </select>
                </div>

                {/* Onboarding Start Date */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Onboarding start date
                  </label>
                  <input
                    type="date"
                    value={onboardingStartDateStr}
                    onChange={(e) => setOnboardingStartDate(parseYYYYMMDD(e.target.value))}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  />
                  <p className="mt-1 text-xs text-gray-500">
                    If the start date is before day {DELIVERABLES_START_DAY_CUTOFF}, the current month is included in the 12 months.
                  </p>
                </div>

                {/* Auto-generate Deliverables */}
                <div className="flex items-start gap-3">
                  <input
                    id="autoGenerateDeliverables"
                    type="checkbox"
                    checked={autoGenerateDeliverables}
                    onChange={(e) => setAutoGenerateDeliverables(e.target.checked)}
                    className="mt-1 h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                  />
                  <div className="flex-1">
                    <label htmlFor="autoGenerateDeliverables" className="text-sm font-medium text-gray-700">
                      Auto-generate 12 months of deliverables
                    </label>
                    <p className="text-xs text-gray-500">
                      Creates monthly deliverable tasks for the next 12 months and assigns them to the selected specialist.
                      {autoGenerateDeliverables ? ` (${getDeliverablesRangeLabel()})` : ""}
                    </p>
                  </div>
                </div>

                {/* Initial Due Date (auto) */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Initial due date
                  </label>
                  <div className="w-full px-3 py-2 border border-gray-200 rounded-lg bg-gray-50 text-sm text-gray-800">
                    {initialDueDateStr} (auto: {INITIAL_DUE_DATE_BUSINESS_DAYS} business days)
                  </div>
                  <p className="mt-1 text-xs text-gray-500">
                    Applies only to tasks #{1}–#{INITIAL_DUE_DATE_TASK_COUNT}. All other tasks require manual due dates.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Selected Template Tasks Preview */}
          {selectedTemplate && (
            <div className="mt-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">
                Tasks to be Created ({selectedTemplate.tasks.length})
              </h3>
              <div className="space-y-3">
                {selectedTemplate.tasks
                  .sort((a, b) => a.order - b.order)
                  .map((task, index) => (
                    <div key={task.id} className="p-4 bg-gray-50 rounded-lg">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center space-x-2">
                            <span className="text-sm font-medium text-gray-500">#{index + 1}</span>
                            <h4 className="font-medium text-gray-900">{task.title}</h4>
                            {task.priority && (
                              <span className={`px-2 py-1 text-xs font-medium rounded-full flex items-center space-x-1 ${getPriorityColor(task.priority)}`}>
                                {getPriorityIcon(task.priority)}
                                <span className="capitalize">{task.priority}</span>
                              </span>
                            )}
                          </div>
                          {task.description && (
                            <p className="text-sm text-gray-600 mt-1">{task.description}</p>
                          )}
                          <div className="flex items-center space-x-4 mt-2 text-xs text-gray-500">
                            {task.category && (
                              <span className="px-2 py-1 bg-gray-200 rounded">
                                {task.category}
                              </span>
                            )}
                            {task.order > 0 && task.order <= INITIAL_DUE_DATE_TASK_COUNT ? (
                              <span className="px-2 py-1 bg-primary-100 text-primary-700 rounded">
                                Due: {initialDueDateStr}
                              </span>
                            ) : (
                              <span className="px-2 py-1 bg-white border border-gray-200 rounded text-gray-500">
                                No due date
                              </span>
                            )}
                            {task.estimatedHours && (
                              <span className="flex items-center space-x-1">
                                <Clock className="h-3 w-3" />
                                <span>{task.estimatedHours}h</span>
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end space-x-3 p-6 border-t border-gray-200 bg-gray-50 flex-shrink-0">
          <button
            onClick={() => setOpen(false)}
            className="px-4 py-2 text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleCreateTasks}
            disabled={loading || !selectedTemplate || !selectedClient}
            className="px-6 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center space-x-2"
          >
            {loading ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                <span>Creating Tasks...</span>
              </>
            ) : (
              <>
                <Plus className="h-4 w-4" />
                <span>
                  Create{" "}
                  {(selectedTemplate?.tasks.length || 0) + (autoGenerateDeliverables ? 12 : 0)}{" "}
                  Tasks
                </span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default OnboardingTemplateModal;
