-- Add SPECIALIST enum value, migrate data, then drop WORKER enum entry
ALTER TABLE `users`
  MODIFY COLUMN `role` ENUM('SUPER_ADMIN','ADMIN','AGENCY','WORKER','SPECIALIST','USER') NOT NULL DEFAULT 'AGENCY';

UPDATE `users`
SET `role` = 'SPECIALIST'
WHERE `role` = 'WORKER';

ALTER TABLE `users`
  MODIFY COLUMN `role` ENUM('SUPER_ADMIN','ADMIN','AGENCY','SPECIALIST','USER') NOT NULL DEFAULT 'AGENCY';
